services:
  - type: web
    name: PlatformRateGraph_app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      python manage.py loaddata data/initial_data.json || true
      gunicorn PlatformRateGraph_app.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      PYTHON_VERSION: 3.11.6
