# Generated by Django 5.2.7 on 2025-11-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配信プラットフォーム名')),
                ('url', models.URLField(verbose_name='公式URL')),
            ],
            options={
                'verbose_name': '配信プラットフォーム',
                'verbose_name_plural': '配信プラットフォーム一覧',
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('organization_name', models.CharField(max_length=100, unique=True, verbose_name='制作会社')),
            ],
            options={
                'verbose_name': '制作会社',
                'verbose_name_plural': '制作会社一覧',
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='アニメタイトル')),
                ('official_url', models.URLField(verbose_name='公式URL')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='common.staffs', verbose_name='制作会社')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品一覧',
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='WorkSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year', models.CharField(max_length=4, verbose_name='放送年')),
                ('season', models.CharField(max_length=2, verbose_name='シーズン')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_season', to='common.works', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品シーズン',
                'verbose_name_plural': '作品シーズン一覧',
                'db_table': 'work_season',
                'unique_together': {('work', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('delivery_start', models.DateField(null=True, verbose_name='配信開始日')),
                ('delivery_end', models.DateField(null=True, verbose_name='配信終了日')),
                ('delivery_count', models.IntegerField(default=0, verbose_name='配信件数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_infos', to='common.platforms', verbose_name='配信プラットフォーム')),
                ('work_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_infos', to='common.workseason', verbose_name='作品シーズン')),
            ],
            options={
                'verbose_name': '配信情報',
                'verbose_name_plural': '配信情報一覧',
                'db_table': 'platform_info',
                'unique_together': {('platform', 'work_season')},
            },
        ),
    ]
