# Generated by Django 5.2.7 on 2025-11-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workseason',
            unique_together={('year', 'season')},
        ),
        migrations.AddField(
            model_name='workseason',
            name='season_delivery_cnt',
            field=models.IntegerField(default=0, verbose_name='シーズン配信件数'),
        ),
        migrations.RemoveField(
            model_name='workseason',
            name='work',
        ),
    ]
