# Generated by Django 5.2.7 on 2025-11-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_workseason_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platforminfo',
            options={'verbose_name': 'PlatformInfo', 'verbose_name_plural': 'PlatformInfos'},
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={'verbose_name': 'PlatForm', 'verbose_name_plural': 'PlatForms'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterModelOptions(
            name='workseason',
            options={'verbose_name': 'WorkSeason', 'verbose_name_plural': 'WorkSeason'},
        ),
    ]
