# Generated by Django 5.2.7 on 2025-12-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_fix_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforminfo',
            name='work_season',
        ),
    ]
