# Generated by Django 4.2.26 on 2025-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_platforminfo_work_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminfo',
            name='batch_key',
            field=models.CharField(db_index=True, default='legacy', max_length=20, verbose_name='登録バッチ識別子'),
        ),
        migrations.AddField(
            model_name='platforms',
            name='batch_key',
            field=models.CharField(db_index=True, default='legacy', max_length=20, verbose_name='登録バッチ識別子'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='batch_key',
            field=models.CharField(db_index=True, default='legacy', max_length=20, verbose_name='登録バッチ識別子'),
        ),
        migrations.AddField(
            model_name='works',
            name='batch_key',
            field=models.CharField(db_index=True, default='legacy', max_length=20, verbose_name='登録バッチ識別子'),
        ),
        migrations.AddField(
            model_name='workseason',
            name='batch_key',
            field=models.CharField(db_index=True, default='legacy', max_length=20, verbose_name='登録バッチ識別子'),
        ),
    ]
